### ISSUE TITLE
view npm-debug.log

### ISSUE THREAD

**Issue by JulianDevilleSmith** [processing-js/processing-js#112]
$ npm install processing
 
> canvas@1.1.6 install /Users/julz/node_modules/processing/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/julz/node_modules/processing/node_modules/canvas
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

> contextify@0.1.8 install /Users/julz/node_modules/processing/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 18, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 534, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 527, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 491, in gyp_main
    'cwd': os.getcwd(),
OSError: [Errno 2] No such file or directory
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/julz/node_modules/processing/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.10.31
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm ERR! canvas@1.1.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.1.6 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 12.5.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "processing"
npm ERR! cwd /Users/julz
npm ERR! node -v v0.10.31
npm ERR! npm -v 2.0.0-beta.0
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/julz/npm-debug.log
npm ERR! not ok code
_____

view npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install', 'processing' ]
2 info using npm@2.0.0-beta.0
3 info using node@v0.10.31
4 verbose node symlink /usr/local/bin/node
5 verbose config Skipping project config: /Users/julz/.npmrc. (matches userconfig)
6 verbose cache add [ 'processing', null ]
7 verbose cache add spec="processing" args=["processing",null]
8 verbose parsed spec { raw: 'processing',
8 verbose parsed spec   scope: null,
8 verbose parsed spec   name: 'processing',
8 verbose parsed spec   rawSpec: '',
8 verbose parsed spec   spec: '*',
8 verbose parsed spec   type: 'range' }
9 verbose addNamed [ 'processing', '*' ]
10 verbose addNamed [ null, '*' ]
11 silly lockFile d5dfeb1b-processing processing@*
12 verbose lock processing@* /Users/julz/.npm/d5dfeb1b-processing.lock
13 silly addNameRange { name: 'processing', range: '*', hasData: false }
14 verbose mapToRegistry name processing
15 verbose mapToRegistry uri https://registry.npmjs.org/processing
16 verbose request on initialization, where is /processing
17 verbose request after pass 1, where is /processing
18 verbose request url raw /processing
19 verbose request resolving registry [ 'https://registry.npmjs.org/', './processing' ]
20 verbose request after pass 2, where is https://registry.npmjs.org/processing
21 verbose request no auth needed
22 info retrier registry request attempt 1 at 17:35:54
23 verbose request id 33663dd8f7229546
24 verbose etag "2QZNH5ICT8DI4Y6TW5ZAHD9PA"
25 http request GET https://registry.npmjs.org/processing
26 http 304 https://registry.npmjs.org/processing
27 silly registry.get cb [ 304,
27 silly registry.get   { date: 'Thu, 28 Aug 2014 07:35:55 GMT',
27 silly registry.get     server: 'Apache',
27 silly registry.get     via: '1.1 varnish',
27 silly registry.get     'last-modified': 'Thu, 28 Aug 2014 07:35:55 GMT',
27 silly registry.get     'cache-control': 'max-age=60',
27 silly registry.get     etag: '"2QZNH5ICT8DI4Y6TW5ZAHD9PA"',
27 silly registry.get     'x-served-by': 'cache-syd1623-SYD',
27 silly registry.get     'x-cache': 'MISS',
27 silly registry.get     'x-cache-hits': '0',
27 silly registry.get     'x-timer': 'S1409211355.207800,VS0,VE238',
27 silly registry.get     vary: 'Accept',
27 silly registry.get     'content-length': '0',
27 silly registry.get     'keep-alive': 'timeout=10, max=50',
27 silly registry.get     connection: 'Keep-Alive' } ]
28 verbose etag https://registry.npmjs.org/processing from cache
29 silly addNameRange number 2 { name: 'processing', range: '*', hasData: true }
30 silly addNameRange versions [ 'processing', [ '0.0.1', '0.1.0', '0.2.0' ] ]
31 verbose addNamed [ 'processing', '0.2.0' ]
32 verbose addNamed [ '0.2.0', '0.2.0' ]
33 silly lockFile d6b2159d-processing-0-2-0 processing@0.2.0
34 verbose lock processing@0.2.0 /Users/julz/.npm/d6b2159d-processing-0-2-0.lock
35 silly lockFile d6b2159d-processing-0-2-0 processing@0.2.0
36 silly lockFile d6b2159d-processing-0-2-0 processing@0.2.0
37 silly lockFile d5dfeb1b-processing processing@*
38 silly lockFile d5dfeb1b-processing processing@*
39 silly resolved [ { author:
39 silly resolved      { name: 'Seiya Konno',
39 silly resolved        email: 'nulltask@gmail.com',
39 silly resolved        url: 'http://null.ly' },
39 silly resolved     name: 'processing',
39 silly resolved     description: 'Processing.js for Node.js',
39 silly resolved     version: '0.2.0',
39 silly resolved     homepage: 'https://github.com/uniba/node-processing',
39 silly resolved     repository: { url: 'git@github.com:uniba/node-processing.git' },

**Comment by Pomax** [comment]
closing due to inactivity
